# 1. 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true    # Rquest & Response에 인코딩 강제
# 2. 스프링 설정
spring:
  # 2-1. DB 접속 정보
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: 1234
  # 2-1. JPA 설정
  jpa:
    open-in-view: true    # 영속성 컨텍스트가 트랜잭션 범위를 넘어서 레이어까지 유지
    hibernate:
      ddl-auto: create    # 기존 테이블이 있음 drop 후 다시 create
    properties:
      hibernate:
        show_sql: false   # 로그에 SQL을 찍는걸 설정해서 false로 설정
        format_sql: true    # 줄맞춤
        highlight_sql: true   # 색깔 표시
# 3. 로그 설정
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"   # 로그 포맺
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
jwt:
  secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb